######################################################################
# Automatically generated by qmake (3.0) Wed Feb 8 06:31:53 2017
######################################################################

TEMPLATE = app
TARGET = HARbrowse
DEPENDPATH += .
INCLUDEPATH += .
QT_PLUGIN_PATH += .
QT += network webkit webkitwidgets
QT += core gui
QT += widgets
CONFIG+=link_pkgconfig
CONFIG+= qt debug
PKGCONFIG+=gstreamer-1.0

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
