######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 15 19:50:25 2017
######################################################################

TEMPLATE = app
TARGET = HARbrowse
DEPENDPATH += .
INCLUDEPATH += .
QT += network webkit
QT += core gui
QT += widgets

# Input
SOURCES += main.cpp 
SOURCES += mainwindow.cpp
HEADERS += mainwindow.h
