######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 13 06:02:57 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
